network:
  name: yc-deploy
  subnets: 
    yc-deploy-subnet:
      v4_cidr_blocks: ["10.5.0.0/24"]
      zone: ru-central1-a


service_accounts:
  yc-deploy-sa:
    roles: 
      - editor
 
instances:
  dev-bastion:
    ansible_groups:
      - bastion
    family_id: ubuntu-2204-lts
    resources:
      cores: 2
      memory: 1 #Gb
      disk_size: 30 #Gb
    network:
      subnet: yc-deploy-subnet
      nat: true
    metadata: 
      ssh-keys: 
        username: ubuntu
        file: ~/.ssh/id_rsa.pub
