network:
  name: yc-deploy
  subnets: 
    yc-deploy-subnet:
      v4_cidr_blocks: ["10.5.0.0/24"]
      zone: ru-central1-a
  ip_addresses:
    alb:
      zone: ru-central1-a

service_accounts:
  yc-deploy-sa:
    roles: 
      - editor
  k8s-main-cp-sa:
    roles:
      - editor
  k8s-main-node-sa:
  ingress-controller:
    roles:
      - alb.editor
      - vpc.publicAdmin
      - certificate-manager.certificates.downloader
      - compute.viewer 
 
# instances:
#   dev-bastion:
#     ansible_groups:
#       - bastion
#     family_id: ubuntu-2204-lts
#     resources:
#       cores: 2
#       memory: 1 #Gb
#       disk_size: 30 #Gb
#     network:
#       subnet: yc-deploy-subnet
#       nat: true
#     metadata: 
#       ssh-keys: 
#         username: ubuntu
#         file: ~/.ssh/id_rsa.pub

kubernetes:
  main:
    version: 1.26
    subnet: yc-deploy-subnet
    public_ip: true
    service_account_name: k8s-main-cp-sa
    node_service_account_name: k8s-main-node-sa
    instance_template:
      name: ig
      count: 2
      cores: 2
      memory: 4
      disk_size: 40
      container_runtime: containerd